---
name: pipeline-check (security compliance)
on:
  pull_request:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  scan:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      actions: read
      pull-requests: write
      security-events: write  # for SARIF upload
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: pipeline-check
        uses: dmartinochoa/pipeline-check@418c80794b02e098fb775a079ebcf86c5859c5b9
...
